name: Build
on: 
  [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Ubuntu GCC
            os: ubuntu-latest
            compiler: gcc
            version: 9
            cc: gcc
            cxx: g++
            generator: Unix Makefiles
            
          - name: Ubuntu Clang
            os: ubuntu-latest
            compiler: clang
            version: 11
            cc: clang
            cxx: clang++
            generator: Unix Makefiles
          
          - name: Windows MSVC
            os: windows-latest
            compiler: Visual Studio
            version: 17
            cc: cl
            cxx: cl
            generator: Visual Studio 17 2022

          - name: Windows MinGW
            os: windows-latest
            version: 11.2
            compiler: gcc
            cc: gcc
            cxx: g++
            generator: MinGW Makefiles
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
            
      - name: CMake configure
        run: >
          cmake -G "${{matrix.config.generator}}" 
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }} 
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx}} 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DWITH_EXAMPLES=1
          -B ${{github.workspace}}/build
                
      - name: Build library
        run: >
          cmake 
          --build ${{github.workspace}}/build 
          --config ${{env.BUILD_TYPE}}
